### PR TITLE
Apply distanceToEdge to FloatingActionItems

### PR DESCRIPTION
**Pull request by khrizt**
Forgot to apply the parameter distanceToEdge to FloatingActionItem

### CODE REVIEW

**Comment by santomegonzalo** [comment]
@khrizt thanks for this code!

**Comment by santomegonzalo** [comment]
@khrizt I found a bug when you set distanceToEdge the actions look weird... I already found a solution so I will be pushing it soon

**Comment by santomegonzalo** [comment]
@khrizt I just merge into **master** with version **1.5.0** a fix for your PullRequest plus I fixed a shadow on iOS

**Comment by khrizt** [comment]
great!! Thanks a lot!

**Pull request merged**
