### PR TITLE
Fixed useNativeDriver warning

### PR DESCRIPTION
**Pull request by ramonvermeulen**
I fixed the useNativeDriver warning since this property is required, since react-native 0.62.0 this property is marked required.

### CODE REVIEW

**Comment by AlimovSV** [comment]
+1

**Comment by msevestre** [comment]
@ramonvermeulen Why would you not want to use the nativeDriver by default? (e.g you set the value to false everywhere)

**Comment by santomegonzalo** [comment]
Merged on https://github.com/santomegonzalo/react-native-floating-action/issues/140... Thanks!

**Comment by AlimovSV** [comment]
@santomegonzalo Please, publish npm package

**Comment by santomegonzalo** [comment]
I'm doing it now... I need to optimize it and do it by github action... I will try to do it with another big PR moving into typescript and hooks

**Comment by AlimovSV** [comment]
@santomegonzalo Thank you very much!

**Comment by santomegonzalo** [comment]
@AlimovSV  it is out now => **react-native-floating-action@1.21.0**

**Comment by ramonvermeulen** [comment]
> @ramonvermeulen Why would you not want to use the nativeDriver by default? (e.g you set the value to false everywhere)

Because native driver is only supported for certain properties (Transform, opacity, and some more). But in a lot of cases it is not supported and will throw a warning.

**Pull request closed without merging**
